<HomeLayout@FloatLayout>:
    Label:
        text: "Welcome to the GZCLP Tracker!"
        font_size: (root.width**2 + root.height**2) / 10.35**4
        halign: 'center'
        size_hint: 1,.2
        pos_hint: {"x":0, "top": 1}
    Label:
        id: lasttime
        text: "Last time you did:\nWorkout Day 1\n\nWhat would you like to do today?"
        halign: 'center'
        font_size: (root.width**2 + root.height**2) / 11**4
        pos_hint: {"x":0, "top": 1}